// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4cJrbMCbvo8vQWklYHjJt4o4WWTMjyKo',
    appId: '1:1089679843288:web:235bdd70a71348773edcad',
    messagingSenderId: '1089679843288',
    projectId: 'tubespapb-40e75',
    authDomain: 'tubespapb-40e75.firebaseapp.com',
    storageBucket: 'tubespapb-40e75.firebasestorage.app',
    measurementId: 'G-5W1RVLRPSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe9f-ZoBSjlgp3d09RiJFFL5OG9_gwF1M',
    appId: '1:1089679843288:android:082fb38e065c12ac3edcad',
    messagingSenderId: '1089679843288',
    projectId: 'tubespapb-40e75',
    storageBucket: 'tubespapb-40e75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-3lxs7NE-3JRjSlP0nWX7-m8CvlxrG8E',
    appId: '1:1089679843288:ios:f41c96d446d8341b3edcad',
    messagingSenderId: '1089679843288',
    projectId: 'tubespapb-40e75',
    storageBucket: 'tubespapb-40e75.firebasestorage.app',
    iosBundleId: 'com.example.tubesfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4cJrbMCbvo8vQWklYHjJt4o4WWTMjyKo',
    appId: '1:1089679843288:web:d39e73168f8749b63edcad',
    messagingSenderId: '1089679843288',
    projectId: 'tubespapb-40e75',
    authDomain: 'tubespapb-40e75.firebaseapp.com',
    storageBucket: 'tubespapb-40e75.firebasestorage.app',
    measurementId: 'G-FQ6N3N4YSD',
  );

}